theme: minima
title: Tamara Niella
author: Tamara Niella
email: tniella@uoregon.edu
description: > # this means to ignore newlines until "baseurl:"
  I am a Ph.D. Canditate in Social Psychology at University of Oregon and Academic Coordinator at the Oxford Consortium for Human Rights. 

# social links
twitter_username: tamaraniella # DO NOT include the @ character, or else the build will fail!
linkedin_username:  tniella # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
